services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules
    environment:
      NODE_ENV: development
      PORT: 3000
    stdin_open: true
    tty: true
    command: npm run dev
  web2:
    build: .
    ports:
      - "3001:3000"
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules
    environment:
      NODE_ENV: development
      PORT: 3000
    stdin_open: true
    tty: true
    command: npm run dev